version: '3.3'

services:

  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8081:8081"
    volumes:
      - "nexus-data:/nexus-data"
      - "./nexus-ssl:/etc/nexus-ssl"
    environment:
      - JAVA_OPTS=-Djavax.net.ssl.trustStore=/etc/nexus-ssl/truststore.jks -Djavax.net.ssl.trustStorePassword=changeit
    restart: unless-stopped

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - "jenkins-data:/var/jenkins_home"
      - ./case_config:/var/jenkins_conf #localy binding the case_config directory to --> (CASC_JENKINS_CONFIG=/var/jenkins_config)
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - CASC_JENKINS_CONFIG=/var/jenkins_config # this is where JCasc configuration file will be residing.
    restart: unless-stopped

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - "sonarqube-data:/opt/sonarqube/data"
      - "sonarqube-extensions:/opt/sonarqube/extensions"
      - "./sonarqube-ssl:/etc/sonarqube-ssl"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_WEB_JVM_OPTS=-Djavax.net.ssl.trustStore=/etc/sonarqube-ssl/truststore.jks -Djavax.net.ssl.trustStorePassword=changeit
    depends_on:
      - sonardb
    restart: unless-stopped

  sonardb:
    image: postgres:latest
    container_name: sonardb
    volumes:
      - "sonardb-data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    restart: unless-stopped

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8090:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
    restart: unless-stopped

volumes:
  nexus-data:
  jenkins-data:
  sonarqube-data:
  sonarqube-extensions:
  sonardb-data:
