version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install
    buid:
      commands:
        - echo Building application...
        - npm run build
artifacts:
  files:
    - out/**
    - next.config.js
    - package.json
    - yarn.lock 
    