# Use the official Node.js image as the base image
FROM node:14

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install project dependencies
RUN npm ci

# Install then-request (or any other additional dependencies you might need)
RUN npm i then-request

# Copy the rest of the application code to the container
COPY . .

# Expose the UDP ports 9005, 9006, and 9007
EXPOSE 9005/udp
EXPOSE 9006/udp
EXPOSE 9007/udp

# Start your Node.js application using pm2
CMD ["pm2", "start", "server.js", "--name", "gv"]
