version: '3'

services:
  sonarqube:
    image: sonarqube
    ports:
      - 9000:9000
    volumes:
      - data:/opt/sonarqube/data
      - logs:/opt/sonarqube/logs
      - extensions:/opt/sonarqube/extensions
    restart: unless-stopped

volumes:
  data:
  logs:
  extensions:
