# # Use an official Node.js runtime as the base image
# FROM node:14
# # Set the working directory in the container
# WORKDIR /app
# # Copy the package.json and package-lock.json files to the container
# COPY package*.json ./
# # Install the dependencies
# RUN npm install
# # Copy the rest of the backend source code to the container
# COPY . .
# # Expose the port on which your Express.js application is listening
# EXPOSE 9000
# # Define the command to run your Express.js application
# CMD ["npm", "start"]


# Use a Node.js base image
FROM node:16

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install application dependencies
RUN npm install

# Copy the application code to the working directory
COPY . .

# Expose port 9000 for the Express.js application
EXPOSE 9000

# Set the environment variables
ENV MONGO_HOST=localhost \
    MONGO_PORT=27017

# Start the Express.js application
CMD [ "npm", "start" ]
