version: '3.3'

services:

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - "sonarqube-data:/opt/sonarqube/data"
      - "sonarqube-extensions:/opt/sonarqube/extensions"
      - "./sonarqube-ssl:/etc/sonarqube-ssl"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_WEB_JVM_OPTS=-Djavax.net.ssl.trustStore=/etc/sonarqube-ssl/truststore.jks -Djavax.net.ssl.trustStorePassword=changeit
    depends_on:
      - sonardb
    restart: unless-stopped

  sonardb:
    image: postgres:latest
    container_name: sonardb
    volumes:
      - "sonardb-data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    restart: unless-stopped

# for jenkins 
  jenkins:
    build: # building docker image
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    ports:
      - 8080:8080
    volumes:
      - "jenkins-data:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock" # Mount the Docker socket file
    restart: unless-stopped

volumes:
  nexus-data:
  jenkins-data:
  sonarqube-data:
  sonarqube-extensions:
  sonardb-data:
 
