version: '3.3'

services:

# for nexus
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8081:8081"
    volumes:
      - "nexus-data:/nexus-data"
      - "./nexus-ssl:/etc/nexus-ssl"
    environment:
      - JAVA_OPTS=-Djavax.net.ssl.trustStore=/etc/nexus-ssl/truststore.jks -Djavax.net.ssl.trustStorePassword=changeit
    restart: unless-stopped