FROM node:18-alpine
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --production

COPY . .

ENV NEXT_TELEMETRY_DISABLED 1

RUN npm run build && \
    rm -rf node_modules && \
    npm install --production --ignore-scripts --prefer-offline

RUN addgroup --system --gid 1001 nodejs \
    && adduser --system --uid 1001 nextjs

USER nextjs

EXPOSE 3000

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1
ENV PORT 3000

CMD ["npm", "start"]
