version: '3.3'

services:

  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8081:8081"
    volumes:
      - "nexus-data:/nexus-data"
      - "./nexus-ssl:/etc/nexus-ssl"
    environment:
      - JAVA_OPTS=-Djavax.net.ssl.trustStore=/etc/nexus-ssl/truststore.jks -Djavax.net.ssl.trustStorePassword=changeit
    restart: unless-stopped

  jenkins:
    image: jenkins/jenkins:2.397
    container_name: jenkins
    ports:
      - 8080:8080
    volumes:
      - "jenkins-data:/var/jenkins_home"
    restart: unless-stopped

volumes:
  nexus-data:
  jenkins-data:
 
